version: "3.1"

services:
  mysqldb:
    container_name: mysqldb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=1
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    restart: always
    volumes:
      - mysqldb:/var/lib/mysql
    image: 'mysql:latest'
  app:
    image: aymenjbara/dockerfile_spring
    container_name: dockerfile_spring
    ports:
      - '8089:8089'
    depends_on:
      - mysqldb
  angularapp:
    depends_on:
      - app
    image: aymenjbara/dockerfile_angular:2.2.2
    container_name: dockerfile_angular
    ports:
      - '4200:80'
volumes:
  mysqldb: { }



